version: '3.8'

services:
  jmeter:
    image: justb4/jmeter:5.5
    volumes:
      - ./jmeter:/jmeter
      - ./results:/results
    working_dir: /jmeter
    entrypoint: [
      "jmeter", "-n", "-t", "./google_search.jmx",
      "-l", "./results/results.jtl",
      "-e", "-o", "./results/html_report",
      "-Jusers=1", "-Jiterations=5", "-Jconstant_time=1000", "-Jrandom_time=10000", "-Jrandom_time_variance=3000"
    ]

