name: Run JMeter Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JMeter and configure XStream whitelist
    - name: Install JMeter and configure whitelist
      run: |
        sudo apt-get update
        sudo apt-get install -y jmeter
        
        # Create a jmeter.properties file with security settings
        echo "xstream.whitelist=org.apache.jmeter.save.ScriptWrapper, com.thoughtworks.xstream.mapper.DynamicProxyMapper" > ./jmeter.properties
        echo "xstream.blacklist=" >> ./jmeter.properties

    # Step 3: Run JMeter test with google_search.jmx
    - name: Run JMeter Test
      run: |
        jmeter -n -t ./google_search.jmx -l results.jtl -q ./jmeter.properties

    # Step 4: Generate HTML report from the results
    - name: Generate JMeter HTML Report
      run: |
        jmeter -g results.jtl -o report-output

    # Step 5: Upload the report as an artifact with an 8-day expiration
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-report
        path: report-output/
        retention-days: 8
