name: Run JMeter Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-jmeter-test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JMeter with Docker
    - name: Run JMeter Test using Docker
      run: |
        docker pull justb4/jmeter:5.5
        docker run --name jmeter-container -v ${{ github.workspace }}:/jmeter -w /jmeter justb4/jmeter:5.5 -n -t ./google_search.jmx -l ./results.jtl

    # Step 3: Generate HTML report from the results using Docker
    - name: Generate JMeter HTML Report
      run: |
        docker run --rm -v ${{ github.workspace }}:/jmeter -w /jmeter justb4/jmeter:5.5 -g ./results.jtl -o ./report-output

    # Step 4: Upload the report as an artifact with an 8-day expiration
    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-report
        path: ./report-output/
        retention-days: 8
