name: JMeter Load Testing with Grafana

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    services:
      influxdb:
        image: influxdb:1.8
        ports:
          - "8086:8086"
        volumes:
          - influxdb_data:/var/lib/influxdb

      grafana:
        image: grafana/grafana:latest
        ports:
          - "3000:3000"
        depends_on:
          - influxdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JMeter
        run: |
          docker pull justb4/jmeter:5.5

      - name: Run JMeter Test
        run: |
          docker run --rm -v ${{ github.workspace }}:/jmeter -w /jmeter justb4/jmeter:5.5 \
          -n -t ./google_search.jmx -l ./results/results.jtl \
          -Jusers=${{ inputs.users }} \
          -Jiterations=${{ inputs.iterations }} \
          -Jconstant_time=${{ inputs.constant_time }} \
          -Jrandom_time=${{ inputs.random_time }} \
          -Jrandom_time_variance=${{ inputs.random_time_variance }}

      - name: Wait for Grafana to be ready
        run: |
          echo "Waiting for Grafana to be ready..."
          sleep 30 # Wait for services to initialize

      - name: Shutdown Grafana after specified time
        run: |
          echo "Shutting down Grafana..."
          sleep 120 # Change this duration as needed
          docker stop $(docker ps -q --filter ancestor=grafana/grafana:latest)

volumes:
  influxdb_data:
