name: JMeter Load Testing

on:
  workflow_dispatch:
    inputs:
      users:
        description: 'Total number of users'
        required: true
        default: '1'
        type: number
      iterations:
        description: 'Number of iterations per user'
        required: true
        default: '1'
        type: number
      constant_time:
        description: 'Constant time after 1 iteration (milliseconds)'
        required: false
        default: '1000'
        type: number
      random_time:
        description: 'Random time after each transaction (milliseconds)'
        required: false
        default: '10000'
        type: number
      random_time_variance:
        description: 'Random time variance (milliseconds)'
        required: false
        default: '3000'
        type: number
      grafana_duration:
        description: 'Grafana dashboard duration (minutes)'
        required: false
        default: '2'
        type: number

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Docker Compose
        run: |
          docker-compose up -d
          echo "Waiting for Grafana to be ready..."
          sleep 30

      - name: Run JMeter Test
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/jmeter \
            -v ${{ github.workspace }}/results:/results \
            -w /jmeter justb4/jmeter:5.5 \
            -n -t ./google_search.jmx -l ./results/results.jtl \
            -Jusers=${{ github.event.inputs.users }} \
            -Jiterations=${{ github.event.inputs.iterations }} \
            -Jconstant_time=${{ github.event.inputs.constant_time }} \
            -Jrandom_time=${{ github.event.inputs.random_time }} \
            -Jrandom_time_variance=${{ github.event.inputs.random_time_variance }}

      - name: Stop Grafana and InfluxDB
        run: |
          sleep $(( ${GRAFANA_DURATION} * 60 ))
          docker-compose down
